import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  parent: {
    flex: 1,
  },
  // 로딩 화면 스타일
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  loadingContent: {
    backgroundColor: "white",
    padding: 30,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
    alignItems: "center",
    minWidth: 250,
  },
  loadingText: {
    marginTop: 20,
    fontSize: 16,
    textAlign: "center",
    color: "#404040",
    lineHeight: 22,
    fontWeight: "500",
  },
  iconLayout: {
    width: 16,
    height: 16,
  },
  textTypo3: {
    lineHeight: 20,
    fontSize: 14,
    letterSpacing: -0.3,
    textAlign: "left",
    fontFamily: "Pretendard",
  },
  frameParentSpaceBlock: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 16,
    gap: 8,
  },
  textTypo: {
    color: "#525252",
    lineHeight: 16,
    letterSpacing: -0.2,
    fontSize: 12,
    textAlign: "left",
    fontFamily: "Pretendard",
  },
  textTypo1: {
    lineHeight: 16,
    letterSpacing: -0.2,
    textAlign: "left",
    fontFamily: "Pretendard",
  },
  frameLayout: {
    height: 80,
    backgroundColor: "#d9d9d9",
    borderRadius: 8,
    overflow: "hidden",
  },
  frameParentFlexBox: {
    gap: 10,
    alignSelf: "stretch",
    flexDirection: "row",
  },
  wrapperFlexBox: {
    paddingVertical: 11,
    paddingHorizontal: 46,
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  view: {
    gap: 16,
    width: "100%",
    flex: 1,
    paddingHorizontal: 16,
  },
  frameParent: {
    width: "100%",
    gap: 4,
  },
  group: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  text: {
    fontSize: 22,
    letterSpacing: -0.4,
    lineHeight: 28,
    textAlign: "left",
    fontFamily: "Pretendard",
    color: "#404040",
    fontWeight: "700",
  },
  calendarDaysIcon: {
    height: 16,
  },
  frameGroup: {
    alignSelf: "stretch",
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  container: {
    alignItems: "center",
    flexDirection: "row",
  },
  text2: {
    color: "#404040",
    fontWeight: "700",
    lineHeight: 20,
    fontSize: 14,
  },
  text3: {
    color: "#404040",
  },
  frameContainer: {
    gap: 8,
    alignSelf: "stretch",
  },
  frameParent2: {
    gap: 4,
  },
  parent2: {
    gap: 8,
    alignItems: "center",
    flexDirection: "row",
  },
  text6: {
    color: "#a3a3a3",
    fontWeight: "700",
    lineHeight: 20,
    fontSize: 14,
  },
  toggle: {
    width: 32,
    height: 16,
  },
  toggleChild: {
    height: "100%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0%",
    borderRadius: 30,
    backgroundColor: "#d4d4d4",
    position: "absolute",
    width: "100%",
  },
  circleIconSets: {
    top: 0,
    left: 0,
    boxShadow: "3px 0px 4.6px rgba(0, 0, 0, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
      width: 3,
      height: 0,
    },
    shadowRadius: 4.6,
    elevation: 4.6,
    shadowOpacity: 1,
    borderRadius: 50,
    backgroundColor: "#fafafa",
    justifyContent: "center",
    position: "absolute",
    height: 16,
    alignItems: "center",
  },
  text7: {
    color: "#a3a3a3",
  },
  frameParent3: {
    alignSelf: "stretch",
    gap: 16,
  },
  frameParent4: {
    width: "100%",
    alignSelf: "stretch",
  },
  frameParent5: {
    justifyContent: "space-between",
    gap: 0,
    alignSelf: "stretch",
    flexDirection: "row",
  },
  frameParent6: {
    gap: 8,
    flexDirection: "row",
  },
  frameChildLayout: {
    height: 24,
    width: 24,
  },
  frameParent7: {
    justifyContent: "center",
  },
  text8: {
    fontSize: 14,
    lineHeight: 24,
    fontWeight: "500",
    letterSpacing: -0.3,
    textAlign: "left",
    color: "#404040",
    fontFamily: "Pretendard",
  },
  frame: {
    borderRadius: 99,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  text9: {
    width: 147,
    alignSelf: "stretch",
  },
  text10: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.2,
    color: "#a3a3a3",
  },
  parent3: {
    width: 95,
    justifyContent: "flex-end",
    gap: 8,
    alignItems: "center",
    flexDirection: "row",
  },
  text11: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.2,
    color: "#404040",
  },
  frameParent8: {
    gap: 8,
    alignSelf: "stretch",
    alignItems: "center",
  },
  frameParent9: {
    gap: 2,
    overflow: "hidden",
    alignSelf: "stretch",
    alignItems: "center",
    flexDirection: "row",
  },
  frameItem: {
    flex: 1,
  },
  text12: {
    marginTop: -8,
    marginLeft: -9.25,
    top: "50%",
    left: "50%",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.2,
    position: "absolute",
    color: "#404040",
  },
  parent4: {
    gap: 7,
    alignItems: "center",
    flexDirection: "row",
  },
  frameIcon: {
    width: 10,
    height: 10,
  },
  lineView: {
    width: "100%",
    borderStyle: "solid",
    borderColor: "#fafafa",
    borderTopWidth: 1,
    height: 1,
  },
  frameParent10: {
    justifyContent: "center",
  },
  wrapper3: {
    flex: 0.3907,
    paddingVertical: 11,
    paddingHorizontal: 46,
    backgroundColor: "#f0f0f0",
  },
  frameWrapper: {
    flexDirection: "row",
    flex: 1,
  },
  wrapper4: {
    flex: 1,
  },
  frameWrapper2: {
    alignSelf: "stretch",
  },
  frameParent11: {
    alignSelf: "stretch",
  },
  frameParent15: {
    backgroundColor: "#f3f3f3",
    padding: 8,
    borderRadius: 8,
    gap: 10,
  },
  wrapper7: {
    width: 28,
    borderRadius: 4,
    backgroundColor: "#ffd2d2",
    padding: 2,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  text20: {
    fontSize: 11,
    color: "#737373",
    fontWeight: "500",
  },
  frameParent16: {
    gap: 2,
    justifyContent: "center",
  },
  frameParent17: {
    gap: 2,
    flexDirection: "row",
  },
  frameChild4: {
    width: 77,
  },
  messageSquareParent: {
    flex: 0.3907,
    paddingVertical: 11,
    paddingHorizontal: 46,
    backgroundColor: "#f0f0f0",
    gap: 4,
  },
  materialSymbolsstarRoundedGroup: {
    gap: 4,
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: "#f0f0f0",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#404040",
    flex: 1,
    textAlign: "center",
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
    paddingBottom: 100, // 하단 버튼 영역만큼 여백 추가
  },
  bottomButtonContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: "#f0f0f0",
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  nextButton: {
    backgroundColor: "#404040",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  nextButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  previewImage: {
    width: "100%",
    height: "100%",
    borderRadius: 8,
  },
  removeButton: {
    position: "absolute",
    top: 5,
    right: 5,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 10,
    padding: 5,
  },
  addImageContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 10,
  },
  addImageButton: {
    alignItems: "center",
    justifyContent: "center",
    width: "45%",
  },
  addImageText: {
    marginTop: 5,
    fontSize: 12,
    color: "#666",
  },
  // 새로운 스타일들
  remainingCountContainer: {
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
  },
  remainingCountOverlay: {
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderRadius: 8,
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  remainingCountText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  actionButton: {
    gap: 6,
    backgroundColor: "#f8f8f8",
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  actionButtonText: {
    color: "#666",
    fontSize: 12,
    fontWeight: "500",
  },
  // 이미지 그리드 스타일들
  imageGridContainer: {
    width: "100%",
    flexDirection: "row",
    gap: 4,
  },
  imageGridContent: {
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 0,
  },
  imageGridItem: {
    backgroundColor: "#d9d9d9",
    borderRadius: 8,
    overflow: "hidden",
    position: "relative",
  },
  singleImageItem: {
    width: "100%",
    height: 120,
  },
  twoImageItem: {
    width: "48%",
    height: 100,
  },
  multiImageItem: {
    width: 80,
    height: 80,
    flexShrink: 0,
  },
  // 평점 입력 UI 스타일
  ratingInputContainer: {
    backgroundColor: "#f8f8f8",
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  ratingLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#404040",
    marginBottom: 8,
  },
  starContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginBottom: 12,
  },
  starButton: {
    padding: 4,
  },
  // 메모 입력 UI 스타일
  memoInputContainer: {
    backgroundColor: "#f8f8f8",
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  memoLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#404040",
    marginBottom: 8,
  },
  memoTextInput: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    minHeight: 80,
    marginBottom: 12,
  },
  // 액션 버튼 스타일
  inputActionButtons: {
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
  },
  saveButton: {
    backgroundColor: "#FF6B9D",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  cancelButton: {
    backgroundColor: "#f0f0f0",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginTop: 8,
    alignSelf: "flex-end",
    borderColor: "#e0e0e0",
  },
  cancelButtonText: {
    color: "#666",
    fontSize: 12,
    fontWeight: "600",
  },
  // 확장 버튼 스타일
  expandButton: {
    alignItems: "center",
    paddingVertical: 8,
  },
  // 평점과 메모 통합 컨테이너 스타일
  ratingMemoContainer: {
    backgroundColor: "#f8f8f8",
    padding: 12,
    borderRadius: 8,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  ratingMemoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  ratingMemoLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#404040",
    marginRight: 8,
  },
  compactStarContainer: {
    flexDirection: "row",
    gap: 4,
  },
  compactStarButton: {
    padding: 2,
  },
  compactMemoInput: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 6,
    padding: 8,
    fontSize: 12,
    minHeight: 40,
    flex: 1,
  },
  compactActionButton: {
    backgroundColor: "#FF6B9D",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginTop: 8,
    alignSelf: "flex-end",
  },
  compactActionButtonText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "600",
  },
});
