import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  parent: {
    flex: 1,
  },
  // 로딩 화면 스타일
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  loadingContent: {
    backgroundColor: "white",
    padding: 30,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
    alignItems: "center",
    minWidth: 250,
  },
  loadingText: {
    marginTop: 20,
    fontSize: 16,
    textAlign: "center",
    color: "#404040",
    lineHeight: 22,
    fontWeight: "500",
  },
  iconLayout: {
    width: 16,
    height: 16,
  },
  textTypo3: {
    lineHeight: 20,
    fontSize: 14,
    letterSpacing: -0.3,
    textAlign: "left",
    fontFamily: "Pretendard",
  },
  frameParentSpaceBlock: {
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderRadius: 16,
    gap: 8,
  },
  textTypo: {
    color: "#525252",
    lineHeight: 16,
    letterSpacing: -0.2,
    fontSize: 12,
    textAlign: "left",
    fontFamily: "Pretendard",
  },
  textTypo1: {
    lineHeight: 16,
    letterSpacing: -0.2,
    textAlign: "left",
    fontFamily: "Pretendard",
  },
  frameLayout: {
    height: 80,
    backgroundColor: "#d9d9d9",
    borderRadius: 8,
    overflow: "hidden",
  },
  frameParentFlexBox: {
    gap: 10,
    alignSelf: "stretch",
    flexDirection: "row",
  },
  wrapperFlexBox: {
    paddingVertical: 11,
    paddingHorizontal: 46,
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  view: {
    gap: 16,
    width: "100%",
    flex: 1,
  },
  frameParent: {
    width: 254,
    gap: 4,
  },
  group: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  text: {
    fontSize: 22,
    letterSpacing: -0.4,
    lineHeight: 28,
    textAlign: "left",
    fontFamily: "Pretendard",
    color: "#404040",
    fontWeight: "700",
  },
  calendarDaysIcon: {
    height: 16,
  },
  frameGroup: {
    alignSelf: "stretch",
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  container: {
    alignItems: "center",
    flexDirection: "row",
  },
  text2: {
    color: "#404040",
    fontWeight: "700",
    lineHeight: 20,
    fontSize: 14,
  },
  text3: {
    color: "#404040",
  },
  frameContainer: {
    gap: 8,
    alignSelf: "stretch",
  },
  frameParent2: {
    gap: 4,
  },
  parent2: {
    gap: 8,
    alignItems: "center",
    flexDirection: "row",
  },
  text6: {
    color: "#a3a3a3",
    fontWeight: "700",
    lineHeight: 20,
    fontSize: 14,
  },
  toggle: {
    width: 32,
    height: 16,
  },
  toggleChild: {
    height: "100%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0%",
    borderRadius: 30,
    backgroundColor: "#d4d4d4",
    position: "absolute",
    width: "100%",
  },
  circleIconSets: {
    top: 0,
    left: 0,
    boxShadow: "3px 0px 4.6px rgba(0, 0, 0, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
      width: 3,
      height: 0,
    },
    shadowRadius: 4.6,
    elevation: 4.6,
    shadowOpacity: 1,
    borderRadius: 50,
    backgroundColor: "#fafafa",
    justifyContent: "center",
    position: "absolute",
    height: 16,
    alignItems: "center",
  },
  text7: {
    color: "#a3a3a3",
  },
  frameParent3: {
    alignSelf: "stretch",
    gap: 16,
  },
  frameParent4: {
    width: 328,
  },
  frameParent5: {
    justifyContent: "space-between",
    gap: 0,
    alignSelf: "stretch",
    flexDirection: "row",
  },
  frameParent6: {
    gap: 8,
    flexDirection: "row",
  },
  frameChildLayout: {
    height: 24,
    width: 24,
  },
  frameParent7: {
    justifyContent: "center",
  },
  text8: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500",
    letterSpacing: -0.3,
    textAlign: "left",
    color: "#404040",
    fontFamily: "Pretendard",
  },
  frame: {
    borderRadius: 99,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  text9: {
    width: 147,
    alignSelf: "stretch",
  },
  text10: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.2,
    color: "#a3a3a3",
  },
  parent3: {
    width: 95,
    justifyContent: "flex-end",
    gap: 8,
    alignItems: "center",
    flexDirection: "row",
  },
  text11: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.2,
    color: "#404040",
  },
  frameParent8: {
    gap: 8,
    alignSelf: "stretch",
    alignItems: "center",
  },
  frameParent9: {
    gap: 2,
    overflow: "hidden",
    alignSelf: "stretch",
    alignItems: "center",
    flexDirection: "row",
  },
  frameItem: {
    flex: 1,
  },
  text12: {
    marginTop: -8,
    marginLeft: -9.25,
    top: "50%",
    left: "50%",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: -0.2,
    position: "absolute",
    color: "#404040",
  },
  parent4: {
    gap: 7,
    alignItems: "center",
    flexDirection: "row",
  },
  frameIcon: {
    width: 10,
    height: 10,
  },
  lineView: {
    width: 313,
    borderStyle: "solid",
    borderColor: "#fafafa",
    borderTopWidth: 1,
    height: 1,
  },
  frameParent10: {
    justifyContent: "center",
  },
  wrapper3: {
    flex: 0.3907,
    paddingVertical: 11,
    paddingHorizontal: 46,
    backgroundColor: "#f0f0f0",
  },
  frameWrapper: {
    flexDirection: "row",
    flex: 1,
  },
  wrapper4: {
    flex: 1,
  },
  frameWrapper2: {
    alignSelf: "stretch",
  },
  frameParent11: {
    alignSelf: "stretch",
  },
  frameParent15: {
    backgroundColor: "#f3f3f3",
    padding: 8,
    borderRadius: 8,
    gap: 10,
  },
  wrapper7: {
    width: 28,
    borderRadius: 4,
    backgroundColor: "#ffd2d2",
    padding: 2,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  text20: {
    fontSize: 11,
    color: "#737373",
    fontWeight: "500",
  },
  frameParent16: {
    gap: 2,
    justifyContent: "center",
  },
  frameParent17: {
    gap: 2,
    flexDirection: "row",
  },
  frameChild4: {
    width: 77,
  },
  messageSquareParent: {
    flex: 0.3907,
    paddingVertical: 11,
    paddingHorizontal: 46,
    backgroundColor: "#f0f0f0",
    gap: 4,
  },
  materialSymbolsstarRoundedGroup: {
    gap: 4,
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: "#f0f0f0",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#404040",
    flex: 1,
    textAlign: "center",
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  bottomButtonContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: "#f0f0f0",
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  nextButton: {
    backgroundColor: "#404040",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  nextButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  previewImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  removeButton: {
    position: "absolute",
    top: 5,
    right: 5,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 10,
    padding: 5,
  },
  addImageContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 10,
  },
  addImageButton: {
    alignItems: "center",
    justifyContent: "center",
    width: "45%",
  },
  addImageText: {
    marginTop: 5,
    fontSize: 12,
    color: "#666",
  },
});
